configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/kthcloud-mxtcme%2Fkthcloud-go-deploy-v2-ccb741a00a9508926373157903a4bab096e54c0bf8098459919cb3bc0dc90ef1.yml
